name: github-actions

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print User Info
        run: |
          echo "ФИО: Алпатов Кирилл Олегович"
          echo "Номер группы: M3114"
          echo "Github : Kirixkes"

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with unittest
        run: |
          python -m unittest discover

      - name: Check code style with flake8
        run: |
          pip install flake8
          flake8 .